version: "3.9"
services:
  nginx:
    # image: nginx
    image: nginx:1.23.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

networks:
  default:
    name: net1
    external: true